### ISSUE TITLE
No space command in bash

### ISSUE THREAD

**Issue by RichieB2B** [SteveClement/misp-refresh#1]
The `space` command in your script seems to print a vertical line in your video. Maybe `space` is an alias for
```
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
```
?

**Comment by SteveClement** [comment]
@RichieB2B the "space" function will be sourced from supportFunctions.
Making it available to the script.

https://github.com/SteveClement/misp-refresh/blob/6bac064c5debb4049ff57c8358166811ca79c425/refresh.sh#L32

**Comment by RichieB2B** [comment]
Ah, nice one! Thanks.
